api:
    resource: "@ApiBundle/Controller/"
    type:     annotation
    prefix:   /api/v1/
    defaults:
        _format: json

app:
    resource: '@AppBundle/Controller/'
    type: annotation

api_login_check:
    path: /api/v1/login_check