# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:

    # https://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        db:
            entity:
                class: ApiBundle\Entity\User
                property: email

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            pattern:  ^/api/v1/login
            anonymous: true
            stateless: true
            provider: db
            form_login:
                check_path:               /api/v1/login_check
                success_handler:          lexik_jwt_authentication.handler.authentication_success
                failure_handler:          lexik_jwt_authentication.handler.authentication_failure
                require_previous_session: false

        api:
           pattern:   ^/api
           stateless: true
           guard:
              authenticators:
                  - lexik_jwt_authentication.jwt_token_authenticator

    access_control:
        - { path: ^/api/v1, role: ROLE_USER, methods: ['GET']}
        - { path: ^/api/v1/checkout, role: ROLE_USER, methods: ['POST']}
        - { path: ^/api/v1, role: ROLE_ADMIN, methods: ['POST', 'PUT', 'DELETE']}

    role_hierarchy:
        ROLE_ADMIN: ROLE_USER

    encoders:
        ApiBundle\Entity\User:
            algorithm: bcrypt