<?php

namespace ApiBundle\Repository;

/**
 * ProductRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductRepository extends \Doctrine\ORM\EntityRepository
{
	public function findAllProducts($search = '')
	{
		$queryBuilder = $this->createQueryBuilder('p');

		if($search) {
			$queryBuilder->andWhere('p.name LIKE :search')
				->setParameter('search', '%' . $search . '%');
		}

		return $queryBuilder;
	}
}
